# Generated by Django 4.0.2 on 2023-08-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
