# Generated by Django 4.0.2 on 2023-08-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_sent_at_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='discription',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
