# Generated by Django 4.0.2 on 2023-08-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_todo_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='discription',
            new_name='description',
        ),
    ]
